services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    container_name: backend
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - mongodb_data:/data/mongodb_data

volumes:
  mongodb_data:
